name: Run Java Tests

on:
  schedule:
    # 毎日午前0時にテストを実行
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ソースコードをチェックアウト
      - name: Check out the repository
        uses: actions/checkout@v3

      # Javaをインストール（ディストリビューションを指定）
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # ここでディストリビューションを指定
          java-version: '17'

      # プロジェクトのルートディレクトリに移動
      - name: Change directory to project folder
        run: cd MyPortfolio  # ここで、pom.xmlが存在するディレクトリに移動

      # Mavenプロジェクトの依存関係をインストール
      - name: Install dependencies
        run: mvn install -DskipTests

      # Mavenテストを実行
      - name: Run tests
        run: mvn test
